---
name: "PlaybackMonitor"
guid: "1cf8cfe3-b20d-42bc-9261-b4ae838a1c98"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "PlaybackMonitor allows server owners to track playback issues"
description: >
  PlaybackMonitor allows server owners to track playback issues, including
  playback start failures, buffering, and transcode errors
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.PlaybackMonitor.dll"
changelog: >
  changelog
